### ISSUE TITLE
[Bug]: Conflict with SvelteKit / Vite / Polyfills

### ISSUE THREAD

**Issue by nostrorom** [wallabyjs/console-ninja#161]
### What happened?

This seems to be sorted as of the latest version, so I'm mostly putting this here so that you have a record that this happen and may or may not happen again:

I and several others were having an issue on SvelteKit projects

```bash
TypeError: Cannot redefine property: crypto
    at Function.defineProperty (<anonymous>)
    at installPolyfills (file:///home/<pathToMyRepo>/node_modules/@sveltejs/kit/src/exports/node/polyfills.js:27:10)
    at dev (file:///home/<pathToMyRepo>/node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:29:3)
    at configureServer (file:///home/<pathToMyRepo>/node_modules/@sveltejs/kit/src/exports/vite/index.js:600:17)
    at _createServer (file:///home/<pathToMyRepo>/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:63461:30)
    at async CAC.<anonymous> (file:///home/<pathToMyRepo>/node_modules/vite/dist/node/cli.js:733:24)
npm ERR! Lifecycle script `dev` failed with error: 
npm ERR! Error: command failed 
npm ERR!   in workspace: @player/web@0.4.2 
npm ERR!   at location: /home/<pathToMyRepo>/apps/web 
ERROR: command finished with error: command (/home/<pathToMyRepo>/apps/web) npm run dev exited (1)
```

See discussion on the [Sveltekit repo](https://github.com/sveltejs/kit/issues/10252) about it - without a full diagnostic of why it seems to have been identified as coming from an interaction with Console Ninja.

Upgrading Console Ninja to at least `0.0.167` has solved the issue for me and some others.

### Version

unsure at time of bug

### Steps to reproduce (or sample repo)

See discussion on the [Sveltekit repo](https://github.com/sveltejs/kit/issues/10252) about it 

### Log output

```shell
TypeError: Cannot redefine property: crypto
    at Function.defineProperty (<anonymous>)
    at installPolyfills (file:///home/<pathToMyRepo>/node_modules/@sveltejs/kit/src/exports/node/polyfills.js:27:10)
    at dev (file:///home/<pathToMyRepo>/node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:29:3)
    at configureServer (file:///home/<pathToMyRepo>/node_modules/@sveltejs/kit/src/exports/vite/index.js:600:17)
    at _createServer (file:///home/<pathToMyRepo>/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:63461:30)
    at async CAC.<anonymous> (file:///home/<pathToMyRepo>/node_modules/vite/dist/node/cli.js:733:24)
npm ERR! Lifecycle script `dev` failed with error: 
npm ERR! Error: command failed 
npm ERR!   in workspace: @player/web@0.4.2 
npm ERR!   at location: /home/<pathToMyRepo>/apps/web 
ERROR: command finished with error: command (/home/<pathToMyRepo>/apps/web) npm run dev exited (1)
```

**Comment by nostrorom** [comment]
All good, I wasn't sure you were aware of, it was just to create a record somewhere :) 

Thanks for the answer and your resolution :+1:
