### ISSUE TITLE
[Bug]: Error: ENOENT: no such file or directory, open '/home/capaj/.vscode/extensions/wallabyjs.console-ninja-1.0.249/out/runtimeHook/tracer.js'

### ISSUE THREAD

**Issue by capaj** [wallabyjs/console-ninja#228]
### What happened?

Error: ENOENT: no such file or directory, open '/home/capaj/.vscode/extensions/wallabyjs.console-ninja-1.0.249/out/runtimeHook/tracer.js'

is thrown when I run vite

### Version

v1.0.253

### Steps to reproduce (or sample repo)

not sure. Seems like it updated in vscode from 1.0.249 to 1.0.253 but there is still some process running in the background which hasn't caught up to this.
restarting vscode does not help. Only thing which helped me to run my project was to remove console.ninja entirely and rm rf node_modules.

### Log output

```shell
lms-fe@0.0.0 dev /home/capaj/work-repos/billie/lms/fe
> vite

node:fs:603
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, open '/home/capaj/.vscode/extensions/wallabyjs.console-ninja-1.0.249/out/runtimeHook/tracer.js'
    at Object.openSync (node:fs:603:3)
    at Object.readFileSync (node:fs:471:35)
    at Z4._createRuntimeHookContent (/home/capaj/.vscode/extensions/wallabyjs.console-ninja-1.0.253/out/buildHook/index.js:1144:776387)
    at Z4._updateConfigDependencies (/home/capaj/.vscode/extensions/wallabyjs.console-ninja-1.0.253/out/buildHook/index.js:1144:774974)
    at Z4._start (/home/capaj/.vscode/extensions/wallabyjs.console-ninja-1.0.253/out/buildHook/index.js:1144:774367)
    at Z4._startIfAllowed (/home/capaj/.vscode/extensions/wallabyjs.console-ninja-1.0.253/out/buildHook/index.js:1144:774254)
    at Z4.start (/home/capaj/.vscode/extensions/wallabyjs.console-ninja-1.0.253/out/buildHook/index.js:1144:773570)
    at Z4._startIfRequired (/home/capaj/.vscode/extensions/wallabyjs.console-ninja-1.0.253/out/buildHook/index.js:1144:772833)
    at new Z4 (/home/capaj/.vscode/extensions/wallabyjs.console-ninja-1.0.253/out/buildHook/index.js:1144:770699)
    at Object.qZ (/home/capaj/.vscode/extensions/wallabyjs.console-ninja-1.0.253/out/buildHook/index.js:1144:769562) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/home/capaj/.vscode/extensions/wallabyjs.console-ninja-1.0.249/out/runtimeHook/tracer.js'
}

Node.js v18.18.0
```

**Comment by smcenlly** [comment]
Thanks for reporting the problem. We will investigate how this may have occurred.

In the meantime, to fix your issue, can you please:

1. Close VS Code
2. Remove and reinstall your node modules for your project
3. Re-open VS Code

This should fix your problem.

**Comment by capaj** [comment]
sure here
[trace.log](https://github.com/wallabyjs/console-ninja/files/13308882/trace.log)

**Comment by ArtemGovorov** [comment]
Thanks for providing the log. While we are still investigating the reason behind the issue, we have released an update that should prevent any Ninja errors from stopping Vite process.
