### ISSUE TITLE
[Bug]: Breaks Next.js build

### ISSUE THREAD

**Issue by rsxdalv** [wallabyjs/console-ninja#257]
### What happened?

Was expecting to build a project but get a completely mysterious error

### Version

0

### Steps to reproduce (or sample repo)

> next build

uncaughtException ReferenceError: rt is not defined
    at C:\Users\admin\Desktop\one-click-installers-tts-main\tts-generation-webui\react-ui\node_modules\next\dist\compiled\webpack\bundle5.js:30:269495
    at finishResolved (C:\Users\admin\Desktop\one-click-installers-tts-main\tts-generation-webui\react-ui\node_modules\next\dist\compiled\webpack\bundle5.js:3:175213)
    at C:\Users\admin\Desktop\one-click-installers-tts-main\tts-generation-webui\react-ui\node_modules\next\dist\compiled\webpack\bundle5.js:3:176097
    at C:\Users\admin\Desktop\one-click-installers-tts-main\tts-generation-webui\react-ui\node_modules\next\dist\compiled\webpack\bundle5.js:3:176889
    at eval (eval at create (C:\Users\admin\Desktop\one-click-installers-tts-main\tts-generation-webui\react-ui\node_modules\next\dist\compiled\webpack\bundle5.js:15:28771), <anonymous>:12:1)
    at C:\Users\admin\Desktop\one-click-installers-tts-main\tts-generation-webui\react-ui\node_modules\next\dist\compiled\webpack\bundle5.js:3:176889
    at eval (eval at create (C:\Users\admin\Desktop\one-click-installers-tts-main\tts-generation-webui\react-ui\node_modules\next\dist\compiled\webpack\bundle5.js:15:28771), <anonymous>:27:1)
    at C:\Users\admin\Desktop\one-click-installers-tts-main\tts-generation-webui\react-ui\node_modules\next\dist\compiled\webpack\bundle5.js:3:160171
    at C:\Users\admin\Desktop\one-click-installers-tts-main\tts-generation-webui\react-ui\node_modules\next\dist\compiled\webpack\bundle5.js:3:176889
    at eval (eval at create (C:\Users\admin\Desktop\one-click-installers-tts-main\tts-generation-webui\react-ui\node_modules\next\dist\compiled\webpack\bundle5.js:15:28771), <anonymous>:12:1)

### Log output

```shell
Upon inspecting this bundle5.js file I see:


!rt || rt.toLowerCase()!='c:\\Users\\admin\\.vscode\\extensions\\wallabyjs.console-ninja-1.0.271\\out\\buildHook\\index.js'.toLowerCase()
```
```

**Comment by rsxdalv** [comment]
[trace.log](https://github.com/wallabyjs/console-ninja/files/13903204/trace.log)

**Comment by rsxdalv** [comment]
Honestly, an extension breaking my build is a bit scary. In retrospect it makes sense but I'll disable it for a while.

**Comment by rsxdalv** [comment]
Disabling it was not enough. I had to do all 3: disable the extension, delete .next and delete node_modules, reinstall and do a clean next build
