### ISSUE TITLE
Console Ninja corrupted yarn with plugin

### ISSUE THREAD

**Issue by AlexXanderGrib** [wallabyjs/console-ninja#37]
After latest update of this extension and tried to run any yarn commands ex: 
```bash
 yarn ts-node src/test.ts
 ```
 
 And i started seeing this error:
 ```javascript
 Internal Error: Cannot find module '/home/alexxgrib/.vscode/extensions/wallabyjs.console-ninja-0.0.18/out/integrations/yarn/plugin.js'
Require stack:
- /home/alexxgrib/.cache/node/corepack/yarn/3.3.0/yarn.js
Require stack:
- /home/alexxgrib/.cache/node/corepack/yarn/3.3.0/yarn.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
    at Module._load (node:internal/modules/cjs/loader:841:27)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (/usr/lib/node_modules/corepack/dist/vcc.js:170:20)
    at o3 (/home/alexxgrib/.cache/node/corepack/yarn/3.3.0/yarn.js:390:10475)
    at Nf (/home/alexxgrib/.cache/node/corepack/yarn/3.3.0/yarn.js:390:11318)
    at D (/home/alexxgrib/.cache/node/corepack/yarn/3.3.0/yarn.js:391:21596)
    at Ga.find (/home/alexxgrib/.cache/node/corepack/yarn/3.3.0/yarn.js:391:22213)
    at async i (/home/alexxgrib/.cache/node/corepack/yarn/3.3.0/yarn.js:446:10711)
    at async t (/home/alexxgrib/.cache/node/corepack/yarn/3.3.0/yarn.js:446:10278)
 ```

**Comment by ArtemGovorov** [comment]
Please try this https://github.com/wallabyjs/console-ninja/issues/11#issuecomment-1342881537, and then restart the editor, it should help.

We'll take a look into why the update of the extension breaks it.

**Comment by ArtemGovorov** [comment]
The error should actually be fixed in the latest version. So once you fix up the file as described here https://github.com/wallabyjs/console-ninja/issues/11#issuecomment-1342881537, it should not happen again.
