### ISSUE TITLE
Console ninja uncaught exception

### ISSUE THREAD

**Issue by Ahmadh26** [wallabyjs/console-ninja#41]
I have recently installed console ninja in my project. 
When i start the project i get the following error in my terminal coming from console ninja: 

```bash 
error - uncaughtException: TypeError: _0x4cf998.startsWith is not a function
    at od (c:\Users\a_4n\.vscode\extensions\wallabyjs.console-ninja-0.0.29\out\buildHook\index.js:1:2104031)
    at Object.lstat (c:\Users\a_4n\.vscode\extensions\wallabyjs.console-ninja-0.0.29\out\buildHook\index.js:1:2108668)
    at lstat (node:fs:1491:11)
    at _rimraf (node:internal/fs/rimraf:68:3)
    at rimraf (node:internal/fs/rimraf:47:3)
    at node:internal/fs/rimraf:146:7
    at Array.forEach (<anonymous>)
    at node:internal/fs/rimraf:143:5
    at FSReqCallback.oncomplete (node:fs:196:23)
```

I am running a nextJS 12 project with typescript. 
Here is a list of my dependencies and dev dependencies if it helps: 

<details>
  <summary>Project Dependencies</summary>
  
  ```js
    "dependencies": {
    "@headlessui/react": "^1.6.5",
    "@hello-pangea/dnd": "^16.0.0",
    "@heroicons/react": "^1.0.6",
    "@next-auth/firebase-adapter": "^1.0.1",
    "@next-auth/prisma-adapter": "^1.0.5",
    "@prisma/client": "^4.7.1",
    "@reduxjs/toolkit": "^1.8.3",
    "@sendgrid/mail": "^7.7.0",
    "@stripe/react-stripe-js": "^1.12.0",
    "@stripe/stripe-js": "^1.38.1",
    "@tailwindcss/line-clamp": "^0.4.2",
    "@tanstack/react-query": "^4.18.0",
    "@tanstack/react-query-devtools": "^4.18.0",
    "chart.js": "^3.9.1",
    "cookies-next": "^2.1.1",
    "date-fns": "^2.29.2",
    "fast-geoip": "^1.1.88",
    "filepond": "^4.30.4",
    "filepond-plugin-file-validate-size": "^2.2.7",
    "filepond-plugin-file-validate-type": "^1.2.8",
    "filepond-plugin-image-crop": "^2.0.6",
    "filepond-plugin-image-edit": "^1.6.3",
    "filepond-plugin-image-exif-orientation": "^1.0.11",
    "filepond-plugin-image-preview": "^4.6.11",
    "filepond-plugin-image-resize": "^2.0.10",
    "filepond-plugin-image-transform": "^3.8.7",
    "firebase": "^9.9.3",
    "flowbite": "^1.4.7",
    "flowbite-react": "^0.0.27",
    "formidable": "^2.0.1",
    "formik": "^2.2.9",
    "geolib": "^3.3.3",
    "google-map-react": "^2.2.0",
    "jose": "^4.10.0",
    "localforage": "^1.10.0",
    "lru-cache": "^7.12.0",
    "mapbox-gl": "^2.10.0",
    "micro": "^9.4.1",
    "moment": "^2.29.3",
    "next": "^12.2.5",
    "next-auth": "^4.16.4",
    "next-seo": "^5.5.0",
    "next-share": "^0.12.1",
    "next-themes": "^0.2.0",
    "nprogress": "^0.2.0",
    "react": "18.2.0",
    "react-chartjs-2": "^4.3.1",
    "react-csv": "^2.2.2",
    "react-date-range": "^1.4.0",
    "react-dom": "18.2.0",
    "react-filepond": "^7.1.2",
    "react-firebase-hooks": "^5.0.3",
    "react-flags-select": "^2.2.3",
    "react-map-gl": "^7.0.19",
    "react-places-autocomplete": "^7.3.0",
    "react-player": "^2.10.1",
    "react-redux": "^8.0.2",
    "react-select": "^5.4.0",
    "react-to-print": "^2.14.7",
    "react-toastify": "^9.0.7",
    "request-ip": "^3.3.0",
    "sharp": "^0.31.2",
    "stripe": "^10.13.0",
    "tailwind-scrollbar-hide": "^1.1.7",
    "yup": "^0.32.11"
  },
  "devDependencies": {
    "@types/formidable": "^2.0.5",
    "@types/geoip-lite": "^1.4.1",
    "@types/google-map-react": "^2.1.7",
    "@types/node": "^18.0.0",
    "@types/nodemailer": "^6.4.4",
    "@types/nprogress": "^0.2.0",
    "@types/react": "18.0.14",
    "@types/react-beautiful-dnd": "^13.1.2",
    "@types/react-csv": "^1.1.3",
    "@types/react-date-range": "^1.4.4",
    "@types/react-dom": "18.0.5",
    "@types/react-places-autocomplete": "^7.2.9",
    "@types/request-ip": "^0.0.37",
    "@types/uuid": "^8.3.4",
    "autoprefixer": "^10.4.7",
    "cross-env": "^7.0.3",
    "eslint": "8.18.0",
    "eslint-config-next": "12.2.0",
    "install": "^0.13.0",
    "npm": "^8.13.2",
    "postcss": "^8.4.14",
    "prisma": "^4.7.1",
    "tailwind-scrollbar": "^1.3.1",
    "tailwindcss": "^3.1.4",
    "ts-node": "^10.8.2",
    "typescript": "^4.7.4"
  },
  ```
</details>

The extension is working, it's just seeing this error on every page i navigate to kinda sucks.

**Comment by ArtemGovorov** [comment]
Can you please try the latest version of extension (v0.0.30)? We've just published it 5 minutes ago, and it should contain the fix for the issue.

Please let us know if the latest version doesn't work for you, and we'll re-open the issue then.
