### ISSUE TITLE
Error in console when starting a Nextjs app

### ISSUE THREAD

**Issue by julianklumpers** [wallabyjs/console-ninja#8]
When starting a Nextjs (v13) app. I'm getting this error in the console. The extension does work regardless of this error.

```sh
error - uncaughtException: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received an instance of Buffer
    at new NodeError (node:internal/errors:371:5)
    at validateString (node:internal/validators:119:11)
    at Object.basename (node:path:1309:5)
    at yc.<computed> [as _errorHandlerTargetFileFilter] (/Users/<user>/.vscode/extensions/wallabyjs.console-ninja-0.0.18/out/buildHook/index.js:1:2103700)
    at yc._shouldInsertErrorHandler (/Users/<user>/.vscode/extensions/wallabyjs.console-ninja-0.0.18/out/buildHook/index.js:1:2111877)
    at yc._allowedToIntercept (/Users/<user>/.vscode/extensions/wallabyjs.console-ninja-0.0.18/out/buildHook/index.js:1:2111695)
    at Object.lstat (/Users/<user>/.vscode/extensions/wallabyjs.console-ninja-0.0.18/out/buildHook/index.js:1:2107462)
    at lstat (node:fs:1439:11)
    at _rimraf (node:internal/fs/rimraf:68:3)
    at rimraf (node:internal/fs/rimraf:47:3) {
  code: 'ERR_INVALID_ARG_TYPE'
```

**Comment by smcenlly** [comment]
Thanks for reporting the problem, this is fixed in Console Ninja `v0.0.20`.
